# Generated by Django 5.2.9 on 2026-03-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot_code', '0002_authorizeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
