# Generated by Django 5.2.9 on 2026-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot_code', '0003_pushtarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('calories', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('carbs', models.FloatField(null=True)),
                ('fat', models.FloatField(null=True)),
                ('basis', models.CharField(blank=True, default='', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTdee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('tdee', models.IntegerField()),
            ],
        ),
    ]
