# Generated by Django 5.2.9 on 2026-03-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot_code', '0004_foodentry_usertdee'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedarticle',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
